### Register Admin User
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "password",
  "password_confirmation": "password",
  "role": "admin"
}

### Login User
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password",
  "role": "admin"
}

### Get Authenticated User Information
GET http://localhost:8000/api/user
Authorization: Bearer 2|VxXG5hTXZIdua26U5VP75oYM1KDR222LYSpZWKOS68928469
Content-Type: application/json

### Logout User
POST http://localhost:8000/api/logout
Authorization: Bearer 2|VxXG5hTXZIdua26U5VP75oYM1KDR222LYSpZWKOS68928469
Content-Type: application/json
