### Listar Estudantes por Admin
GET http://localhost:8000/api/admin/students
Authorization: Bearer 1|k4wCGWpZVxcb3buu9CO3dXGqvZKY0sMkgBvlD2z891496932
Content-Type: application/json

### Listar Estudante e curso
GET http://localhost:8000/api/admin/students/2
Authorization: Bearer 1|k4wCGWpZVxcb3buu9CO3dXGqvZKY0sMkgBvlD2z891496932
Content-Type: application/json