### Register Student User
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "Gabriel Sta",
  "email": "gabrielsta@example.com",
  "password": "password",
  "password_confirmation": "password",
  "role": "student",
  "admin_id": 8
}

### Login User
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "gabrielsta@example.com",
  "password": "password",
  "role": "student"
}

### Get Authenticated User Information
GET http://localhost:8000/api/user
Authorization: Bearer 6|Fqg7u3qkZhMy83qRN3R7NW39tQvHcnFe7dvyhg9Jf0f05e08
Content-Type: application/json

### Logout User
POST http://localhost:8000/api/logout
Authorization: Bearer 6|Fqg7u3qkZhMy83qRN3R7NW39tQvHcnFe7dvyhg9Jf0f05e08
Content-Type: application/json
