### Listar Cursos
GET http://localhost:8000/api/student/course
Authorization: Bearer 6|Fqg7u3qkZhMy83qRN3R7NW39tQvHcnFe7dvyhg9Jf0f05e08
Content-Type: application/json

### Mostrar Curso Específico
GET http://localhost:8000/api/student/course/1
Authorization: Bearer 6|Fqg7u3qkZhMy83qRN3R7NW39tQvHcnFe7dvyhg9Jf0f05e08
Content-Type: application/json

### Atualizar Status de um Curso
PUT http://localhost:8000/api/student/course/1
Authorization: Bearer 6|Fqg7u3qkZhMy83qRN3R7NW39tQvHcnFe7dvyhg9Jf0f05e08
Content-Type: application/json

{
  "status": "COMPLETED"
}